model:
    name: 'XGBoostRULPredictor'
train_test_split:
    name: 'RandomTrainTestSplitter'
    cell_data_path: 'data/processed/NASA'
    train_test_split_ratio: 0.7
feature:
    name: 'DischargeModelFeatureExtractor'
label:
    name: 'RULLabelAnnotator'
feature_transformation:
    name: 'ZScoreDataTransformation'
label_transformation:
    name: 'SequentialDataTransformation'
    transformations:
        - name: 'LogScaleDataTransformation'
        - name: 'ZScoreDataTransformation'
